version: "3.7"
 
networks:
  default:
    driver: bridge
 
services:
 
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: nestdb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8088:80"

  nestdb:
    image: mysql:5.7.32
    container_name: nestdb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - nestjsdb:/var/lib/mysql/
    networks:
      - default
    
volumes:
  nestjsdb:
    driver: local